# Generated by Django 4.2 on 2023-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aginy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='content',
            field=models.TextField(verbose_name='Message history'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='datetime',
            field=models.DateTimeField(verbose_name='Date and time of chat'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Chat title'),
        ),
    ]
